FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libgomp1 \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -U pip \
  && pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY docs ./docs
COPY data ./data

ENV PORT=8080

# worker doesn't need to listen on 8080
CMD ["python", "-m", "app.workers.cloudrun_worker"]
